from dotenv import load_dotenv
import os
from langchain_ollama import ChatOllama
from langchain_core.prompts import PromptTemplate
from langchain_docling.loader import DoclingLoader
from langchain.tools import tool
from langchain_core.messages import HumanMessage 
from tavily import TavilyClient
from langchain_tavily import TavilySearch
from langchain.agents import create_agent
from pydantic import BaseModel, Field
from typing import List

load_dotenv()

def document_loader(path):
    loader = DoclingLoader(file_path=path)
    information = ""
    for document in loader.lazy_load(): 
        information += document.page_content
    return information

def ai_chain():

    information = document_loader("./data/docs/health_api_doc.pdf")
    summary_template = '''
    Given the information about health API doccument {information}, summarize the key points in a concise manner.
    '''
    summary_prompt_template = PromptTemplate(input_variables=["information"], template=summary_template)

    llm = ChatOllama(model="gemma4:latest", base_url=os.environ["OLLAMA_ENDPOINT"])
    chain = summary_prompt_template | llm
    llm_response = chain.invoke(input={"information": information})
    print(llm_response.content)

#########################################################################################
@tool
def search(query: str) -> dict:
    '''Performs a web search using the Tavily API and returns the results.'''
    client = TavilyClient()
    response = client.search(query=query, num_results=5)
    return response

class Source(BaseModel):
    '''Represents a source url of information.'''
    url: str = Field(description="The URL of the source used to generate the answer")

class AgentResponse(BaseModel):
    '''Represents the response from the agent, including the answer and the sources used.'''
    answer: str = Field(description="The answer generated by the agent")
    sources: List[Source] = Field(default_factory=list, description="List of sources used to generate the answer")


def ai_agent():

    llm = ChatOllama(model="gemma4:latest", base_url=os.environ["OLLAMA_ENDPOINT"])

    agent = create_agent(model=llm, tools=[TavilySearch()], response_format=AgentResponse)

    result = agent.invoke({"messages": [HumanMessage(content="Who is the CM of tamilnadu?")]})

    print(result["messages"][-1].content)
    #print(result["messages"][-1])
#########################################################################################

def main():
    #ai_chain()
    ai_agent()


if __name__ == "__main__":
    main()
